# RuboCop configuration for slim-lint integration
# This file configures RuboCop cops that are used by slim-lint

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

# Enable all cops by default, then disable specific ones
# This ensures new cops are automatically enabled

# Layout cops
Layout:
  Enabled: true

# Lint cops
Lint:
  Enabled: true

# Metrics cops
Metrics:
  Enabled: true

# Naming cops
Naming:
  Enabled: true

# Style cops
Style:
  Enabled: true

# Disable specific cops that are problematic for slim-lint
# These match the ignored_cops in .slim-lint.yml
Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false 