name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['18.x', '20.x', '22.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: npm ci

      - name: Install slim-lint via Bundler
        run: |
          bundle install
          bundle exec slim-lint --version

      - name: Setup virtual display (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Compile TypeScript
        run: npm run compile

      - name: Run tests
        run: npm test
        env:
          DISPLAY: ${{ matrix.os == 'ubuntu-latest' && ':99' || '' }}
          ELECTRON_DISABLE_SANDBOX: 'true'
          ELECTRON_NO_ATTACH_CONSOLE: 'true'
          ELECTRON_ENABLE_LOGGING: 'false'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.node-version }}
          path: |
            out/test/
            .vscode-test/
          retention-days: 7

  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with auto-fix
        run: npm run lint:fix

      - name: Format code
        run: npm run format

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code formatting changes detected. Please run 'npm run format' and commit the changes."
            git diff
            exit 1
          fi
